"""empty message

Revision ID: 0149e0e85e74
Revises: 649edd8a1879
Create Date: 2025-12-07 01:02:08.908756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0149e0e85e74'
down_revision = '649edd8a1879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('genero', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('genero')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
