"""primeiro migrate

Revision ID: 8d98157c86b3
Revises: 
Create Date: 2025-09-28 11:14:35.415270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d98157c86b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('data_registo', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formas_pagamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.Enum('Pequeno', 'Médio', 'Grande', 'SUV', 'Luxo'), nullable=False),
    sa.Column('transmissao', sa.Enum('Automático', 'Manual'), nullable=False),
    sa.Column('tipo_veiculo', sa.Enum('Carro', 'Motor'), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('valor_diaria', sa.Float(), nullable=False),
    sa.Column('imagem_url', sa.String(length=100), nullable=True),
    sa.Column('data_ultima_revisao', sa.String(length=10), nullable=True),
    sa.Column('data_proxima_revisao', sa.String(length=10), nullable=True),
    sa.Column('data_ultima_inspecao', sa.String(length=10), nullable=True),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.String(length=10), nullable=False),
    sa.Column('data_fim', sa.String(length=10), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('forma_pagamento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['forma_pagamento_id'], ['formas_pagamento.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas')
    op.drop_table('veiculos')
    op.drop_table('formas_pagamento')
    op.drop_table('clientes')
    # ### end Alembic commands ###
