"""modification

Revision ID: d60f6ffb5a71
Revises: 425ab804d0df
Create Date: 2025-10-27 14:19:31.447851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60f6ffb5a71'
down_revision = '425ab804d0df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_ultima_revisao', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('data_proxima_revisao', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('data_ultima_inspecao', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_cadastro', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.drop_column('data_cadastro')
        batch_op.drop_column('ativo')
        batch_op.drop_column('data_ultima_inspecao')
        batch_op.drop_column('data_proxima_revisao')
        batch_op.drop_column('data_ultima_revisao')

    # ### end Alembic commands ###
